### ISSUE TITLE
Xcode error

### ISSUE THREAD

**Issue by Nazarash** [nicegram/Nicegram-iOS#171]
When I try to generate an Xcode project, terminal show me an error:

 python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
No matching processes belonging to you were found
**ERROR:** Error computing the main repository mapping: Every .bzl file must have a corresponding package, but '@@rules_xcodeproj//xcodeproj:repositories.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
Computing main repo mapping: 
Traceback (most recent call last):
  File "/Users/nik/Downloads/Nicegram-iOS-build-232/build-system/Make/Make.py", line 1049, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/nik/Downloads/Nicegram-iOS-build-232/build-system/Make/Make.py", line 566, in generate_project
    generate(
  File "/Users/nik/Downloads/Nicegram-iOS-build-232/build-system/Make/ProjectGeneration.py", line 58, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/nik/Downloads/Nicegram-iOS-build-232/build-system/Make/ProjectGeneration.py", line 51, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/nik/Downloads/Nicegram-iOS-build-232/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/nik/Downloads/Nicegram-iOS-build-232/build-input/bazel-7.0.2-darwin-arm64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/nik/Downloads/Nicegram-iOS-build-232/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.
nazarasuraliev@MacBook-Pro-Nazar Nicegram-iOS-build-232 %

**Comment by Aadarsh805** [comment]
same

```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
ERROR: /Users/aadarsh805/Nicegram-iOS/WORKSPACE:19:17: fetching local_repository rule //external:rules_xcodeproj: java.io.IOException: No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/aadarsh805/Nicegram-iOS/build-system/bazel-rules/rules_xcodeproj
ERROR: Error computing the main repository mapping: no such package '@@rules_xcodeproj//xcodeproj': No MODULE.bazel, REPO.bazel, or WORKSPACE file found in /Users/aadarsh805/Nicegram-iOS/build-system/bazel-rules/rules_xcodeproj
Computing main repo mapping:
Traceback (most recent call last):
  File "/Users/aadarsh805/Nicegram-iOS/build-system/Make/Make.py", line 1049, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/aadarsh805/Nicegram-iOS/build-system/Make/Make.py", line 566, in generate_project
    generate(
  File "/Users/aadarsh805/Nicegram-iOS/build-system/Make/ProjectGeneration.py", line 58, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/aadarsh805/Nicegram-iOS/build-system/Make/ProjectGeneration.py", line 51, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/aadarsh805/Nicegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/aadarsh805/Nicegram-iOS/build-input/bazel-7.1.1-darwin-arm64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/aadarsh805/Nicegram-iOS/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.
```
